name: CI

on: [push, workflow_dispatch]

jobs:
  build-yt-dlp:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run autobuild-yt-dlp.cmd
      run: |
        cd yt-dlp
        python.exe -m pip install --upgrade pip
        cat autobuild-yt-dlp.cmd | cmd
    - name: Generate Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: yt-dlp-windows-latest-${{ matrix.python-version }}
        path: yt-dlp/yt_dlp/
        compression-level: 9
        retention-days: 90
        if-no-files-found: error
